# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Nayana Prakash
description: >- # this means to ignore newlines until "baseurl:"
  "Nayana Prakash's personal webpage."
baseurl: "/npwebsite" # the subpath of the site
url: "https://pgilders.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Teaching

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: nayana.prakash@oii.ox.ac.uk
      link: mailto:nayana.prakash@oii.ox.ac.uk
#     - name: WeChat
#       value: YourWeChatUsername
#       link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/NayanaPrakash1
      username: "@NayanaPrakash1"
#     - name: Facebook
#       link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://uk.linkedin.com/in/nayana-prakash-b6b12387
#     - name: GitHub
#       link: http://github.com/YourGitHubUsername
#     - name: Dribbble
#       link: https://dribbble.com/YourDribbbleUsername
#     - name: RSS
#       link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
